### ISSUE TITLE
Make Install Fails on Ubuntu 18.10

### ISSUE THREAD

**Issue by joesixpack** [lightstreams-network/lightchain#129]
#### System information
```
Lightchain version: 1.0.0
OS & version: Ubuntu 18.10
Branch: master
Commit hash: 

```
#### Expected behaviour
Should successfully compile lightchain.

#### Actual behaviour
Fails.

#### Steps to reproduce the behaviour
sudo apt-get install golang-go go-dep
make get_vendor_deps
make install

#### Console output (if applicable)

````
j@j-desktop:~/go/src/github.com/lightstreams-network/lightchain$ make install
go install ./cmd/lightchain
# github.com/lightstreams-network/lightchain/vendor/gopkg.in/olebedev/go-duktape.v3
duk_logging.c: In function ‘duk__logger_prototype_log_shared’:
duk_logging.c:184:64: warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
                                                                ^
In file included from /usr/include/stdio.h:867,
                 from duk_logging.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 25 and 85 bytes into a destination of size 32
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

**Comment by ggarri** [comment]
HI @joesixpack, firstly thanks for your feedback and sorry for our delay in replying.

I just created a new docker instance with the same OS version you specify above and the compilation completed successfully. Would you mind to provide your `$> go version` and `$> dep version` output?

```
$> go version
go version go1.10.3 linux/amd64
```

```
$> dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

If that is a blocking issue for you we are publishing pre-compiled binaries for Linux and MacOS. See the instructions on our [documentation](https://docs.lightstreams.network/getting-started/install/#lightchain)

**Comment by ggarri** [comment]
In case you are using a  Go 1.12+ your issue might be sorted after the work done this another reported issue https://github.com/lightstreams-network/lightchain/issues/128. Could you confirm if that was the case?
