### ISSUE TITLE
`eth_estimateGas` rpc call does not work

### ISSUE THREAD

**Issue by ggarri** [lightstreams-network/lightchain#134]
The call of go-ethereum method
```
client.Connection.EstimateGas(ctx, *msg)
```

Throws an exception with the following message:
```
gas required exceeds allowance or always failing transaction
```

**Comment by emizzle** [comment]
I can confirm this is happening when connecting to a lightnode via web3.

**Comment by emizzle** [comment]
On the contrary, I was attempted to `.deploy().estimateGas()` with incorrect arguments. @ggarri - double-check you have the correct args for the tx.

**Comment by ggarri** [comment]
Hi @emizzle, thanks for your collaboration. 

The same implementation was validated using Ganache and on Rinkeby network, therefore, we got to believe that there is a misconfiguration on the usage of go-ethereum code we have for lightchain. 

We will be working on it very soon.

**Comment by ggarri** [comment]
I just executed the following RPC call against our Sirius network 
```
curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to": "0x109aa384b8786e55abfa1f0ac6cb0561e0a06e94", "from": "0xdf4221b931b6ad4f4f221e2eb03913bd4368d0ba"}],"id":1}' http://localhost:8545
```
And correctly output 21000 in HEX
```
{"jsonrpc":"2.0","id":1,"result":"0x5208"}
```

**Comment by ggarri** [comment]
I added a test to validate the correctness on the output of `eth_estimateGas`

**Comment by ggarri** [comment]
After research on the original source of this error, I realized we were using a very old version of go-ethereum library which seems to be causing the issue. During the usage of `go-ethereum` v1.8.27 I could not reproduce the same issue, therefore I am inclined to resolve this issue till further cases on same topic come up
