### ISSUE TITLE
lightchain init/run tracelog default value path

### ISSUE THREAD

**Issue by iris-garcia** [lightstreams-network/lightchain#137]
# Description
While setting up two client nodes in the same server following the guide https://docs.lightstreams.network/guides/exchange-integration/ the first client network works fine but when you try to setup the second one you face an error:
```
ERROR[05-01|13:07:01.718] open /tmp/tracer.log: permission denied  module=lightchain
```
Basically there are some defaultArgs added to the *lightchain* cmd and even if you do not specify 
the trace option, it creates the /tmp/tracer.log file with the permissions 644.

# Todo
The ideal solution would be to place the tracer.log file under the --datadir path given as argument.
Another option would be to rename tracer.log to any unique name.

**Comment by EnchanterIO** [comment]
+1. There are more problems with running 2 lightchain nodes on the same instance. Especially ports collision. You can get by this issue with using `leth` and specifying --nodeid.

E.g:

`leth init --nodeid=1 --network=sirius`
`leth init --nodeid=2 --network=sirius`

And then u can boot both of them without problems on the same machine. We should make this for Lightchain as well.

**Comment by ggarri** [comment]
As a quick workaround in meanwhile this issue is sorted, you can set 777 permissions as follow:

```bash
chmod 777 /tmp/tracer.log
```
