### ISSUE TITLE
[URGENT] Investigate client node corrupt state 

### ISSUE THREAD

**Issue by ggarri** [lightstreams-network/lightchain#146]
## Description

It was reported to us that one of the client nodes of Sirius came across a corrupt state after the client node was closed for a couple of days.

Provided screenshot:
![Image Pasted at 2019-5-21 16-20](https://user-images.githubusercontent.com/2728080/58111877-95616180-7bf2-11e9-9055-a8d325d00201.png)

## Additional information
- User informed us that he shut his node around the time the [block 39983](https://explorer.sirius.lightstreams.io/block/399823) was created.
- User Lightchain version: `Version: 1.1.2-beta MainNet`

**Comment by ggarri** [comment]
## Highlighted facts after quick investigation
- The block 39983 appears to include a [TX](https://explorer.sirius.lightstreams.io/tx/0x91c76e300ae4a7069375447c058047283ad1041149c6452d4411b22a35c425c2) which performed a smart contract deployment.
- A new release was done upgrading the version of Geth less than 12 hours before the block 39983 was created. Update correspond to this [PR](https://github.com/lightstreams-network/lightchain/pull/140)

**Comment by ggarri** [comment]
Evaluating the possibility that the update of `go-ethereum` library from 1.8.23 to 1.8.27 was the root of the issue we collected the following facts:
- Merge of v1.1.2 was done May 16 10.16 UTC
- Deploy of version 1.1.2 was only done over Sirius Sentry nodes and on 16 May 10.50 UTC
- Affected block happened on 17 May 07.53 UTC.
- [Block 398888](https://explorer.sirius.lightstreams.io/block/398888) happened at 15.10 UTC includes more txs
- Lukas synchronized his local node using version 1.1.0 without any issue
- Gabriel synchronized his local node using version 1.1.2 without any issue 

Due to the above reasons, we could deem that the root of the problem is not related to the upgrade on go-ethereum

**Comment by ggarri** [comment]
According to the client, he closed the node around the same time the block 39983 was created, assuming it happened at the exact time. Assuming that the action performed during the closing time of the node are the following:

```go
func (db *Database) Stop() error {
	db.ethTxSub.Unsubscribe()
	db.eth.BlockChain().Stop()
	db.eth.Engine().Close()
	db.eth.TxPool().Stop()
	db.eth.ChainDb().Close()
	return nil
}
``` [Code](https://github.com/lightstreams-network/lightchain/blob/e95e957ca856e5d8ce22294348df2a25ac481cbd/database/database.go#L160)

That stopping actions were copied from the PoW behaviour of Ethereum nodes and might be the cause of this issue. My guessing at the moment leads to the point that when the user shit his local node the state is local db state persisted without the approval of the consensus protocol leading to this corrupt state.

### Next steps
In order to evaluate this theory, we need to run two nodes connected to the same network. On one of the node, we are going to continuously run txs in meanwhile on the other node we close and restore the synchronization. 

In the case of reproducing the state of the affected client we will need to write the `func (db *Database) Stop() error {` impl

**Comment by EnchanterIO** [comment]
Could be related to https://github.com/lightstreams-network/lightchain/issues/122. Maybe one of the `Close()` are returning an error we are ignoring or a method is async and we don't give it enough time to terminate.

**Comment by ggarri** [comment]
After a deep look into this issue, we got to reproduce the same state in our local nodes.

We found that during the `blockchain.stop()` process the latest block is being persisted using the `root` hash (AppHash) of the parent block ignoring the possible state changes occur during the current block as following code extracted from `blockchain.stop()` confirms:
```
log.Info("Writing cached state to disk", "block", recent.Number(), "hash", recent.Hash(), "root", recent.Root())
				if err := triedb.Commit(recent.Root(), true); err != nil {
					log.Error("Failed to commit recent state trie", "err", err)
				}
```

That makes sense as every invalid block AppHash correspond to block including a tx in it.

**Comment by ggarri** [comment]
It was possible to reproduce the corrupted state by executing a tx on my local node having my local clock out of sync.
