### ISSUE TITLE
Official Lightchain docker image

### ISSUE THREAD

**Issue by 0x13a** [lightstreams-network/lightchain#170]
I was wondering if you had an official lightchain docker image on docker hub or any other container registry

**Comment by EnchanterIO** [comment]
Not yet, I will set it up and upload right now. One sec.

**Comment by EnchanterIO** [comment]
@0x13a it will take a bit longer, blocked by: https://github.com/lightstreams-network/lightchain/issues/171

**Comment by EnchanterIO** [comment]
Done @0x13a : https://hub.docker.com/r/lightstreams/lightchain

**Comment by joesixpack** [comment]
Please set the tag "latest" so Docker finds by default.
