### ISSUE TITLE
Make the --datadir flag optional 

### ISSUE THREAD

**Issue by azappella** [lightstreams-network/lightchain#49]
## Actual result
The two following command require the --datadir flag:
```
lightchain init --datadir=~/.lightchain
lightchain run --datadir=~/.lightchain
```
## Expected result
The following two commands should default to ~/.lightchain by default, so that the user does not have to type the --datadir flag for no reason: 
```
lightchain init
lightchain run 
```

**Comment by ggarri** [comment]
Duplicated #60

**Comment by EnchanterIO** [comment]
This is not a duplicate Gabri, I am reopening the task.
